## Server Config
server:
  port: 5005
  servlet:
    context-path: /api

  ## DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miPresupuesto?useSSL=false&serverTimezone=UTC
    username: root
    password: Kumple22*zu+
    initialization-mode: always
  application:
    name: presupuesto-api

  ## JPA/Hibernate Properties
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
        storage_engine: innodb
        show_sql: true
        format_sql: true
    open-in-view: false